version: "3.8"
services:
  db_database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogging_api
      MYSQL_USER: blogging_user
      MYSQL_PASSWORD: blogging_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
    